const { facebookAuthVerify } = require("./facebook-auth.js");

// the test account is generated by facebook developer center.
// visit your facebook app for managing test users.
// the access token will be renewed when you try to "get an new access token" via app setting.
// so make sure to sync accessToken here when you run "get an new access token".

const testAccount = {
  id:          "103601270286638",
  name:        "Sharon Alaiajbieifcb Martinazziberg",
  email:       "ttjchibnmk_1499263537@tfbnw.net",
  accessToken: "EAAB3JvAbdLkBABrklm4E4k69bNm93wgsrUsmiZC8DLXFbF1m15QY65ntKq14bac4MgkrHqPnjq6o7Nwpp72rL2szf7n6AmfyxJtPrWt4qaUqUmfX5kBkwEJIVCRIV9rvl2OH7JdWZBgxehfXjtnHOtZAfo9HBGIKOYtxB9HKZAZArQRZB0gYr81dWUeI6N5Nz6QpZCvzAfQQnhZAEYba34czxz7BIVhzVCLuimv7uCHawwZDZD"
};

describe("utils/facebook-auth.js", () => {
  it("should successfully verify", async () => {
    const result = await facebookAuthVerify({ userId: testAccount.id, accessToken: testAccount.accessToken });
    expect(result).toBeDefined();
  });

  it("should fail", () => {
    expect(facebookAuthVerify({ userId: "103601270286638", accessToken: "weeee" })).rejects.toBeDefined();
  });
});
